### ISSUE TITLE
Incompatible to symfony 3.2

### ISSUE THREAD

**Issue by pboethig** [phlib/console-process#1]
Hi,
Cool stuff!.

If i run the command on the demoncommand I get this exception
[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: Declaration of Phlib\ConsoleProcess\Command\BackgroundCommand::set  
  Code($code) should be compatible with Symfony\Component\Console\Command\Com  
  mand::setCode(callable $code) 

looks like they typehinted the interfacemethod

**Comment by qubit05** [comment]
Hi,

Thanks for reporting this. I'll take a look as soon as I can.

**Comment by qubit05** [comment]
Reproduced against updated Symfony Console Component.

[Symfony Console Command Commit](https://github.com/symfony/console/commit/99726c81b9fcf88b4c157f552caf1e7d4832fdef#diff-25a75e093c4a0d5564a36cebbb1384b3)

Symfony Console version 3.2.1

**Comment by qubit05** [comment]
Fixed in release 0.7 (pre-release)
