### ISSUE TITLE
Error with background

### ISSUE THREAD

**Issue by Paul75** [phlib/console-process#2]
Hello,

When execute I have error :

`"message": "Notice: Use of undefined constant SIGTERM - assumed 'SIGTERM'",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/opt/app-root/src/api/vendor/phlib/console-process/src/Command/BackgroundCommand.php",
            "line": 46,
            "args": []
        },
        {
            "namespace": "Phlib\\ConsoleProcess\\Command",
            "short_class": "BackgroundCommand",
            "class": "Phlib\\ConsoleProcess\\Command\\BackgroundCommand",
            "type": "->",
            "function": "__construct",
            "args": []
        },
        {
            "namespace": "",
            "short_class": "ReflectionClass",
            "class": "ReflectionClass",
            "type": "->",
            "function": "newInstance",
            "file": "/opt/app-root/src/api/var/cache/dev/classes.php",
            "line": 3649,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel\\Bundle",
            "short_class": "Bundle",
            "class": "Symfony\\Component\\HttpKernel\\Bundle\\Bundle",
            "type": "->",
            "function": "registerCommands",
            "file": "/opt/app-root/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php",
            "line": 143,
            "args": [
                [
                    "object",
                    "Symfony\\Bundle\\FrameworkBundle\\Console\\Application"
                ]
            ]
        },
        {
            "namespace": "Symfony\\Bundle\\FrameworkBundle\\Console",
            "short_class": "Application",
            "class": "Symfony\\Bundle\\FrameworkBundle\\Console\\Application",
            "type": "->",
            "function": "registerCommands",
            "file": "/opt/app-root/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php",
            "line": 124,
            "args": []
        },
        {
            "namespace": "Symfony\\Bundle\\FrameworkBundle\\Console",
            "short_class": "Application",
            "class": "Symfony\\Bundle\\FrameworkBundle\\Console\\Application",
            "type": "->",
            "function": "add",
            "file": "/opt/app-root/src/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php",
            "line": 89,
            "args": [
                [
                    "object",
                    "Symfony\\Component\\Console\\Command\\HelpCommand"
                ]
            ]
        },
        {
            "namespace": "Symfony\\Component\\Console",
            "short_class": "Application",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->",
            "function": "__construct",
            "file": "/opt/app-root/src/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php",
            "line": 43,
            "args": [
                [
                    "string",
                    "Symfony"
                ],
                [
                    "string",
                    "3.2.10"
                ]
            ]
        },
        {
            "namespace": "Symfony\\Bundle\\FrameworkBundle\\Console",
            "short_class": "Application",
            "class": "Symfony\\Bundle\\FrameworkBundle\\Console\\Application",
            "type": "->",
            "function": "__construct",
            "file": "/opt/app-root/src/api/src/AppBundle/Controller/PrivateAPI/BatchsController.php",
            "line": 68,
            "args": [
                [
                    "object",
                    "AppKernel"
                ]
            ]
        },
....`

Thanks

**Comment by qubit05** [comment]
Hi,

The SIGTERM constant comes from the PCNTL extension. This package requires that extension in order to run. There is a requirement in the composer file which should have informed you when installing.

http://php.net/manual/en/pcntl.constants.php

Hope this helps.
